# Generated by Django 4.1.7 on 2023-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_report_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_image',
            field=models.ImageField(blank=True, default='', help_text='up to 20 reports', upload_to=''),
        ),
    ]
